type ExpandedSkill = Record<string, number>
type CharacterSkills = {
    anthropology: number
    archeology: number
    longFirearms: ExpandedSkill
    shortFirearms: number
    disguise: number
    electrecity: number
    smallTalk: number
    history: number
    horseRiding: number
    foreignTounge: ExpandedSkill
    motherTounge: ExpandedSkill
    libraryUsage: number
    accounting: number
    wealth: number
    mechanic: number
    healthcare: number
    cthulhuMythos: number
    listening: number
    science: ExpandedSkill
    navigation: number
    heavyEqiupmentUsage: number
    occultism: number
    persuasion: number
    firstAid: number
    flying: number
    swimming: number
    law: number
    carRiding: number
    psychoanalisys: number
    psychology: number
    throwing: number
    jumping: number
    perception: number
    artAndCraft: ExpandedSkill
    survival: ExpandedSkill
    locksmithing: number
    tracking: number
    hiding: number
    dodge: number
    charm: number
    brawl: ExpandedSkill
    natureKnowledge: number
    climbing: number
    barter: number
    intimidation: number
}
export default CharacterSkills