import CharacterData from "@/types/characterData";
import CharacterSkills from "@/types/characterSkills";
import { CharacterTraits } from "@/types/characterTraits";
export const initCharData = (): CharacterData => {
  return {
    characterName: "",
    age: -1,
    description: "",
    domicile: "",
    gender: "M",
    ideology: "",
    importantPeople: "",
    importantPlaces: "",
    job: null,
    mysteryItems: "",
    perks: "",
    personalBelongings: "",
    phobias: "",
    placeOfBirth: "",
    scars: "",
    strangeEncounters: "",
  };
};
export const initCharacterTraits = (): CharacterTraits => {
  return {
    strength: 0,
    constitution: 0,
    dexterity: 0,
    intelligence: 0,
    apperance: 0,
    power: 0,
    size: 0,
    move: 8,
    education: 0,
    healthPoints: 0,
    sanityPoints: 0,
    magicPoints: 0,
    luckPoints: 0,
    damageMod: 0,
    build: 0,
  };
};
export const initCharacterSkills = (): CharacterSkills => {
  return {
    anthropology: 0,
    archeology: 0,
    longFirearms: {},
    shortFirearms: 0,
    disguise: 0,
    electrecity: 0,
    smallTalk: 0,
    history: 0,
    horseRiding: 0,
    foreignTounge: {},
    motherTounge: {},
    libraryUsage: 0,
    accounting: 0,
    wealth: 0,
    mechanic: 0,
    healthcare: 0,
    cthulhuMythos: 0,
    listening: 0,
    science: {},
    navigation: 0,
    heavyEqiupmentUsage: 0,
    occultism: 0,
    persuasion: 0,
    firstAid: 0,
    flying: 0,
    swimming: 0,
    law: 0,
    carRiding: 0,
    psychoanalisys: 0,
    psychology: 0,
    throwing: 0,
    jumping: 0,
    perception: 0,
    artAndCraft: {},
    survival: {},
    locksmithing: 0,
    tracking: 0,
    hiding: 0,
    dodge: 0,
    charm: 0,
    brawl: {},
    natureKnowledge: 0,
    climbing: 0,
    barter: 0,
    intimidation: 0,
  };
};
